### ISSUE TITLE
Unable to build with Vision Camera 3.0.0-rc4

### ISSUE THREAD

**Issue by DeveloperMCD** [rodgomesc/vision-camera-code-scanner#156]
I'm on React-Native 0.72.4, React-Native-Vision-Camera 3.0.0-rc4

Getting this error:

/home/matthew/dev/stackbayapp/node_modules/vision-camera-code-scanner/android/src/main/java/com/visioncameracodescanner/VisionCameraCodeScannerPlugin.java:40: error: VisionCameraCodeScannerPlugin is not abstract and does not override abstract method callback(Frame,ReadableNativeMap) in FrameProcessorPlugin
public class VisionCameraCodeScannerPlugin extends FrameProcessorPlugin {
       ^
/home/matthew/dev/stackbayapp/node_modules/vision-camera-code-scanner/android/src/main/java/com/visioncameracodescanner/VisionCameraCodeScannerPlugin.java:62: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/matthew/dev/stackbayapp/node_modules/vision-camera-code-scanner/android/src/main/java/com/visioncameracodescanner/VisionCameraCodeScannerPlugin.java:251: error: constructor FrameProcessorPlugin in class FrameProcessorPlugin cannot be applied to given types;
    super("scanCodes");
    ^
  required: no arguments
  found:    String
  reason: actual and formal argument lists differ in length
/home/matthew/dev/stackbayapp/node_modules/vision-camera-code-scanner/android/src/main/java/com/visioncameracodescanner/VisionCameraCodeScannerPluginPackage.java:19: error: cannot find symbol
    FrameProcessorPlugin.register(new VisionCameraCodeScannerPlugin());
                        ^
  symbol:   method register(VisionCameraCodeScannerPlugin)
  location: class FrameProcessorPlugin
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vision-camera-code-scanner:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by marouane-edghoughi** [comment]
Currently facing the same problem, did you manage to solve it?

**Comment by tyanbiao** [comment]
Same error 😭

**Comment by DeveloperMCD** [comment]
I'm still getting this error when I add vision-camera-code-scanner to my project, even though 3.0.0-rc5 (with the new react-native-worklets-core) builds fine for Android on my PC.

I'm even using the updated branch, which is supposed to work with Vision Camera v3 (circa April 2023).
I think the recent major changes to v3 are causing a problem. Maybe?

**Comment by joacub** [comment]
any advance in this ?

**Comment by marouane-edghoughi** [comment]
@DeveloperMCD  Unfortunately, we're still facing the same issue even after using your v3 barcode scanner.

**Comment by DeveloperMCD** [comment]
Yes, as I said in the OP, the updated fork which is supposed to work with the "March 2023 version" of Vision Camera v3 does not currently build. I tried RC3 and the latest RCs as well.

Someone's going to have to dig into the code and update it again, I guess. 

Let's be clear; I didn't do any of the coding on this fork. I just grabbed RKMackinnon's  fork so I could publish it to a public NPM registry (and thus easily include it in React Native projects).

Now the real hard work begins though -- someone needs to help fix this library (Vision Camera Code Scanner) which is been completely abandoned -- and apparently there are < 1 current contributors to this project: i.e., people who know the code and/or willing to contribute and/or have the skills to bring it up to speed.

**Comment by DeveloperMCD** [comment]
I'll tell you what though: the MacKinnon fork is certainly the starting point you want to start from. It's the best version or collection of code for "Vision Camera Code Scanner" on the planet right now. It has all the fixes that currently exist somewhere. MacKinnon started out by bringing the whole thing up to speed with V3, albeit the March 2023 version. If you started from the original Vision Camera Code Scanner, you'd have a lot more work to do.

The problem is, there's more fixing to do now. But it's not like those fixes can be found in some repository anywhere on the planet yet. It's work yet-to-be-done.

**Comment by mohammadgharouni** [comment]
any updates?

**Comment by Nanle21** [comment]
> I'm still getting this error when I add vision-camera-code-scanner to my project, even though 3.0.0-rc5 (with the new react-native-worklets-core) builds fine for Android on my PC.
> 
> I'm even using the updated branch (from rkmackinnon), which is supposed to work with Vision Camera v3 (circa March 2023). I think the recent major changes to v3 are causing a problem. Maybe?
> 
> What I'm using right now: Vision Camera: 3.0.0-rc5 This plugin: https://www.npmjs.com/package/vision-camera-v3-barcode-scanner React-Native-Worklets-Core: 0.2.0

This doesn't seem to work also

**Comment by sabarinath-m** [comment]
Facing the same issue here. any solution yet?
I got this issue after upgrading from RN 0.71.10 to RN 0.72.4

**Comment by DeveloperMCD** [comment]
Using RKMacKinnon's latest changes, I got everything to build successfully. However, when I try to use the library, I get some new errors now:

 ERROR  Error: Exception in HostFunction: java.lang.NullPointerException: getPlugin(name, options) must not be null, js engine: hermes
 ERROR  Error: Exception in HostFunction: java.lang.NullPointerException: getPlugin(name, options) must not be null, js engine: hermes
 ERROR  TypeError: Cannot read property 'scanBarcodes' of undefined

**Comment by DeveloperMCD** [comment]
https://www.npmjs.com/package/vision-camera-v3-barcode-scanner

The readme is a bit out of date -- I renamed the package to "vision-camera-v3-barcode-scanner" when I published it publicly to NPM.

import {BarcodeFormat, useScanBarcodes, scanBarcodes} from 'vision-camera-v3-barcode-scanner';

**Comment by JackHull** [comment]
Still encountering this error.

**Comment by wangjh7** [comment]
same error

**Comment by wangjh7** [comment]
> https://www.npmjs.com/package/vision-camera-v3-barcode-scanner
> 
> The readme is a bit out of date -- I renamed the package to "vision-camera-v3-barcode-scanner" when I published it publicly to NPM.
> 
> import {BarcodeFormat, useScanBarcodes, scanBarcodes} from 'vision-camera-v3-barcode-scanner';

I tried and it built successfully, Great Job!
I noticed that https://github.com/mrousavy/react-native-vision-camera/pull/1466#issue-1577662880, **__scanQRCodes(frame)** is deprecated in v3, and I assume that the **globals: ['__scanCodes']** config can be removed, right?

**Comment by chandubudda** [comment]
anyone have solution for this error, still facing error

**Comment by chandubudda** [comment]
VisionCamera: Frame Processors enabled!
CMake Error in CMakeLists.txt:
  Imported target "react-native-worklets-core::rnworklets" includes
  non-existent path

i am still geting this error while building android

**Comment by chandubudda** [comment]
> https://www.npmjs.com/package/vision-camera-v3-barcode-scanner
> 
> The readme is a bit out of date -- I renamed the package to "vision-camera-v3-barcode-scanner" when I published it publicly to NPM.
> 
> import {BarcodeFormat, useScanBarcodes, scanBarcodes} from 'vision-camera-v3-barcode-scanner';

VisionCamera: Frame Processors enabled!
CMake Error in CMakeLists.txt:
Imported target "react-native-worklets-core::rnworklets" includes
non-existent path

i am still facing this issue

**Comment by agunbuhori** [comment]
same error

**Comment by manish0707** [comment]
> same error

+1

**Comment by samcodeng** [comment]
check this out guys, react-native-vision-camera now does QR/Barcode scanning
https://www.react-native-vision-camera.com/docs/guides/code-scanning

**Comment by mgcrea** [comment]
I've also just released a frame processor rebuilt for vision-camera 3+ that can do high (configurable) fps scanning and provides highlighting of detected barcodes out-of-the-box. 

You can check a working demo on GitHub [@mgcrea/vision-camera-barcode-scanner](https://github.com/mgcrea/vision-camera-barcode-scanner).

Hope it can help others.

**Comment by natemartins** [comment]
> I've also just released a frame processor rebuilt for vision-camera 3+ that can do high (configurable) fps scanning and provides highlighting of detected barcodes out-of-the-box.
> 
> You can check a working demo on GitHub [@mgcrea/vision-camera-barcode-scanner](https://github.com/mgcrea/vision-camera-barcode-scanner).
> 
> Hope it can help others.

Does this work on apps that use `react-native-reanimated` `v3` and above? I have been stuck on getting this to work for the past 5 hours but no head way.

This is the error I'm getting

```
Execution failed for task ':react-native-vision-camera:buildCMakeDebug[arm64-v8a]'
```

**Comment by mgcrea** [comment]
@natemartins I had android issues as well in the past but they went away, can you try the latest version [v0.5.1](https://github.com/mgcrea/vision-camera-barcode-scanner/releases/tag/0.5.1) and see if you still encounter issues building vision-camera?

**Comment by manish0707** [comment]
Updating minSdkVersion to 26 solved this issue for me for now in android.

Looking for a better solution if available.

**Comment by natemartins** [comment]
@mgcrea Updating to [v0.5.1](https://github.com/mgcrea/vision-camera-barcode-scanner/releases/tag/0.5.1) fixed it.

Note that you would have to set `minSdkVersion` to `26` if you're on a version lower than 26. Thanks to @manish0707 for pointing this out

**Comment by DominicTobias** [comment]
Nevermind, somehow `vision-camera-code-scanner` was still in my `yarn.lock`, explicitly removing it fixed the error
![Screenshot 2023-10-10 at 4 38 43 PM](https://github.com/rodgomesc/vision-camera-code-scanner/assets/760314/9522b935-6600-45cb-8939-a25e0b195249)
